version: '3.3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - PORT=27017
      - MONGO_USERNAME=cassandra
      - MONGO_PASSWORD=bigtable
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo:4.0
    ports:
      - "27017:27017"

  test:
    build: .
    command: mix test 
    ports:
      - 4002:4002
    environment:
      - MIX_ENV=test
      - PORT=4002
      - PORT=27017
    volumes:
      - .:/app
    depends_on:
      - db-test

  db-test:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
